name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Nightly
      run: rustup toolchain install nightly
    - name: run nightly evn
      run: rustup run nightly
    - name: Buld bilbil-live
      run: cargo build
    - name: Build release
      run: cargo build --release
